# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ModelService_pb2 as ModelService__pb2


class ModelRunnerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.run = channel.unary_unary(
        '/tensormarket.ModelRunner/run',
        request_serializer=ModelService__pb2.JsonMsg.SerializeToString,
        response_deserializer=ModelService__pb2.JsonMsg.FromString,
        )


class ModelRunnerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def run(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ModelRunnerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'run': grpc.unary_unary_rpc_method_handler(
          servicer.run,
          request_deserializer=ModelService__pb2.JsonMsg.FromString,
          response_serializer=ModelService__pb2.JsonMsg.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'tensormarket.ModelRunner', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
