# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ModelService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ModelService.proto',
  package='tensormarket',
  syntax='proto3',
  serialized_pb=_b('\n\x12ModelService.proto\x12\x0ctensormarket\"\x16\n\x07JsonMsg\x12\x0b\n\x03msg\x18\x01 \x01(\t2D\n\x0bModelRunner\x12\x35\n\x03run\x12\x15.tensormarket.JsonMsg\x1a\x15.tensormarket.JsonMsg\"\x00\x62\x06proto3')
)




_JSONMSG = _descriptor.Descriptor(
  name='JsonMsg',
  full_name='tensormarket.JsonMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='tensormarket.JsonMsg.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=58,
)

DESCRIPTOR.message_types_by_name['JsonMsg'] = _JSONMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JsonMsg = _reflection.GeneratedProtocolMessageType('JsonMsg', (_message.Message,), dict(
  DESCRIPTOR = _JSONMSG,
  __module__ = 'ModelService_pb2'
  # @@protoc_insertion_point(class_scope:tensormarket.JsonMsg)
  ))
_sym_db.RegisterMessage(JsonMsg)



_MODELRUNNER = _descriptor.ServiceDescriptor(
  name='ModelRunner',
  full_name='tensormarket.ModelRunner',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=60,
  serialized_end=128,
  methods=[
  _descriptor.MethodDescriptor(
    name='run',
    full_name='tensormarket.ModelRunner.run',
    index=0,
    containing_service=None,
    input_type=_JSONMSG,
    output_type=_JSONMSG,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODELRUNNER)

DESCRIPTOR.services_by_name['ModelRunner'] = _MODELRUNNER

# @@protoc_insertion_point(module_scope)
